"""Mirror Malcontent executable blocklists into the kernel execution policy."""

from __future__ import annotations

import hashlib
import os
import stat
import subprocess
import tempfile
import threading
from pathlib import Path


class ExecutionPolicyError(RuntimeError):
    """The execution policy could not be generated or activated safely."""


class FapolicydPolicy:
    """Maintain the product-owned fapolicyd deny rules.

    Malcontent filters launchers in GNOME Shell, but callers which open a
    trusted ``.desktop`` file directly bypass that UI check.  fapolicyd's
    execute permission event closes that second launch path.
    """

    def __init__(
            self,
            rules_path: Path = Path(
                "/etc/fapolicyd/rules.d/89-oh-no-parent-control.rules"
            ),
            reload_command=("/usr/sbin/fagenrules", "--load")):
        self._rules_path = rules_path
        self._reload_command = tuple(reload_command)
        self._lock = threading.Lock()

    @staticmethod
    def _digest(path: str) -> str:
        flags = os.O_RDONLY | getattr(os, "O_CLOEXEC", 0) | getattr(os, "O_NOFOLLOW", 0)
        try:
            descriptor = os.open(path, flags)
        except FileNotFoundError:
            raise
        except OSError as error:
            raise ExecutionPolicyError(f"blocked executable is unavailable: {path}") from error
        try:
            before = os.fstat(descriptor)
            if not stat.S_ISREG(before.st_mode):
                raise ExecutionPolicyError(f"blocked executable is not a regular file: {path}")
            digest = hashlib.sha256()
            with os.fdopen(descriptor, "rb", closefd=False) as stream:
                for block in iter(lambda: stream.read(1024 * 1024), b""):
                    digest.update(block)
            after = os.fstat(descriptor)
            if (before.st_dev, before.st_ino, before.st_size, before.st_mtime_ns) != (
                    after.st_dev, after.st_ino, after.st_size, after.st_mtime_ns):
                raise ExecutionPolicyError(f"blocked executable changed while hashing: {path}")
            return digest.hexdigest()
        finally:
            os.close(descriptor)

    @classmethod
    def _object_clause(cls, target: str) -> str:
        # fapolicyd 1.3 splits rules on whitespace and commas and offers no
        # quoting for path= values.  Use the executable identity for those
        # valid filesystem names instead of emitting a rule which cannot parse.
        if any(character.isspace() for character in target) or "," in target:
            return f"sha256hash={cls._digest(target)}"
        return f"path={target}"

    @classmethod
    def render(cls, filters: dict[int, tuple[str, ...]]) -> str:
        lines = [
            "# Generated by Oh No! Parent Control. Do not edit.",
        ]
        for uid in sorted(filters):
            if type(uid) is not int or not 0 < uid <= (1 << 32) - 1:
                raise ExecutionPolicyError("invalid execution-policy UID")
            for target in sorted(set(filters[uid])):
                # Flatpak refs are enforced by Malcontent/Flatpak. fapolicyd
                # rules apply only to native executable paths.
                if not target.startswith("/"):
                    continue
                try:
                    clause = cls._object_clause(target)
                except FileNotFoundError:
                    # Saved policies intentionally survive uninstalled apps.
                    # A missing object cannot execute and therefore needs no
                    # current kernel rule.
                    continue
                lines.append(
                    f"deny_syslog perm=execute uid={uid} : {clause}"
                )
        return "\n".join(lines) + "\n"

    def reconcile(self, filters: dict[int, tuple[str, ...]]) -> None:
        contents = self.render(filters)
        with self._lock:
            previous = None
            try:
                previous = self._rules_path.read_bytes()
            except FileNotFoundError:
                pass
            except OSError as error:
                raise ExecutionPolicyError("could not read current execution policy") from error

            if previous == contents.encode("utf-8"):
                return

            self._replace(contents.encode("utf-8"))
            try:
                self._reload()
            except Exception as error:
                try:
                    if previous is None:
                        self._rules_path.unlink(missing_ok=True)
                    else:
                        self._replace(previous)
                    self._reload()
                except Exception as rollback_error:
                    raise ExecutionPolicyError(
                        "execution-policy rollback could not be activated"
                    ) from rollback_error
                if isinstance(error, ExecutionPolicyError):
                    raise
                raise ExecutionPolicyError("execution policy could not be activated") from error

    def _replace(self, contents: bytes) -> None:
        try:
            self._rules_path.parent.mkdir(parents=True, exist_ok=True, mode=0o755)
            descriptor, temporary = tempfile.mkstemp(
                prefix=f".{self._rules_path.name}.", dir=self._rules_path.parent,
            )
            try:
                with os.fdopen(descriptor, "wb") as stream:
                    stream.write(contents)
                    stream.flush()
                    os.fsync(stream.fileno())
                os.chmod(temporary, 0o644)
                os.replace(temporary, self._rules_path)
            finally:
                if os.path.exists(temporary):
                    os.unlink(temporary)
        except OSError as error:
            raise ExecutionPolicyError("could not write execution policy") from error

    def _reload(self) -> None:
        try:
            completed = subprocess.run(
                self._reload_command,
                stdin=subprocess.DEVNULL,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
                timeout=15,
                text=True,
            )
        except (OSError, subprocess.SubprocessError) as error:
            raise ExecutionPolicyError("could not reload execution policy") from error
        if completed.returncode != 0:
            raise ExecutionPolicyError("could not reload execution policy")
