#!/usr/bin/python3
import sys

sys.path.insert(0, "/usr/lib/oh-no-parent-control/parent")
sys.path.insert(0, "/usr/lib/oh-no-parent-control")

from oh_no_parent_control_parent.main import main

raise SystemExit(main())
