"""Schema-first diagnostics. Never format an exception or an unknown payload.

Only this module creates diagnostic LogRecords. The catalog is shipped code,
not customer configuration. Field sources must be reviewed with each call site;
types alone cannot determine whether a number represents personal information.
"""

from contextlib import contextmanager
from contextvars import ContextVar
from datetime import datetime
from functools import wraps
import json
import logging
import math
import re
from pathlib import Path
import sys
import threading
import uuid

SCHEMA_VERSION = 1
MAX_EVENT_BYTES = 4096
CATALOG = json.loads(Path(__file__).with_name("diagnostic_catalog.json").read_text())
LEVELS = {"DEBUG": 10, "INFO": 20, "WARNING": 30, "ERROR": 40, "CRITICAL": 50}
COMPONENTS = {"broker", "parent", "child", "kiosk"}
_operation = ContextVar("diagnostic_operation", default=0)
_operation_counter = 0
_operation_lock = threading.Lock()


def error_code(error):
    """Return a closed category without calling str/repr on the exception."""
    name = type(error).__name__
    return name if name in ERROR_CODES else "other"


ERROR_CODES = frozenset((
    "other", "Error", "ValueError", "TypeError", "KeyError", "RuntimeError",
    "OSError", "PermissionError", "FileNotFoundError", "TimeoutError",
    "TimeoutExpired", "CalledProcessError", "BackendFailure", "AccessDenied",
    "InvalidRequest", "Busy", "ConfigurationError", "ExecutionPolicyError",
    "RequestException", "ConnectionError", "ConnectTimeout", "ReadTimeout",
    "SSLError", "JSONDecodeError", "CancelledError", "MigrationError",
    "RateLimited", "RollbackFailure", "TimerUsageError", "UninstallCleanupError",
))


def _field(spec, value, *, normalize=False):
    kind = spec["type"]
    if kind == "enum":
        if type(value) is str and value in spec["values"]:
            return value
        if normalize:
            return "other"
    elif kind == "bool":
        if type(value) is bool:
            return value
    elif kind == "int":
        if type(value) is int and spec["min"] <= value <= spec["max"]:
            return value
    elif kind == "number":
        if (type(value) in (int, float) and spec["min"] <= value <= spec["max"]
                and math.isfinite(value)):
            return round(value, 3)
    elif kind == "request":
        # Correlation cookies are random operation references generated by the
        # broker, never account/session/device identifiers or hashes of them.
        if type(value) is str and len(value) == 36:
            try:
                parsed = uuid.UUID(value)
                if parsed.version == 4 and str(parsed) == value:
                    return value
            except ValueError:
                pass
    elif kind == "version":
        if type(value) is str and (value == "unknown" or re.fullmatch(r"[0-9]{1,4}(?:\.[0-9]{1,4}){1,3}", value)):
            return value
    elif kind == "local-timestamp":
        if (type(value) is str and re.fullmatch(
                r"[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}[+-][0-9]{2}:[0-9]{2}", value)):
            try:
                parsed = datetime.fromisoformat(value)
                if parsed.isoformat(timespec="milliseconds") == value:
                    return value
            except ValueError:
                pass
    raise ValueError("Invalid diagnostic field")


def event(event_id, values=None, *, normalize=False, operation=0):
    if type(event_id) is not str or event_id not in CATALOG:
        raise ValueError("Unknown diagnostic event")
    definition = CATALOG[event_id]
    fields = definition["fields"]
    values = {} if values is None else values
    if type(values) is not dict or values.keys() != fields.keys():
        raise ValueError("Invalid diagnostic fields")
    if type(operation) is not int or not 0 <= operation <= 2**31 - 1:
        raise ValueError("Invalid diagnostic operation")
    return {"v": SCHEMA_VERSION, "event": event_id, "operation": operation,
            "fields": {key: _field(spec, values[key], normalize=normalize)
                       for key, spec in fields.items()}}


def decode(payload, *, component=None):
    if type(payload) is not str or len(payload.encode("utf-8")) > MAX_EVENT_BYTES:
        raise ValueError("Invalid diagnostic envelope")
    try:
        value = json.loads(payload)
    except (ValueError, RecursionError) as error:
        raise ValueError("Invalid diagnostic envelope") from None
    if (type(value) is not dict or set(value) != {"v", "event", "fields", "operation"}
            or type(value["v"]) is not int or value["v"] != SCHEMA_VERSION):
        raise ValueError("Invalid diagnostic envelope")
    safe = event(value["event"], value["fields"], operation=value["operation"])
    if component is not None and component not in CATALOG[safe["event"]]["components"]:
        raise ValueError("Invalid diagnostic source")
    return safe


def encode(value):
    return json.dumps(value, ensure_ascii=True, separators=(",", ":"), sort_keys=True)


def describe(value):
    """Readable support output uses only catalog text and validated fields."""
    definition = CATALOG[value["event"]]
    return f"onpc.{definition['domain']} " + definition["description"].format_map(value["fields"])


@contextmanager
def operation():
    global _operation_counter
    with _operation_lock:
        _operation_counter = _operation_counter % (2**31 - 1) + 1
        number = _operation_counter
    token = _operation.set(number)
    try:
        yield number
    finally:
        _operation.reset(token)


class EventLogger:
    def __init__(self, domain):
        self.domain = domain
        self.name = "onpc." + domain

    def _emit(self, level, event_id, values, named):
        try:
            definition = CATALOG[event_id]
            if definition["domain"] != self.domain:
                raise ValueError("Invalid diagnostic domain")
            if values:
                if named or len(values) != len(definition["fields"]):
                    raise ValueError("Invalid diagnostic fields")
                named = dict(zip(definition["fields"], values))
            safe = event(event_id, named, normalize=True, operation=_operation.get())
        except (KeyError, TypeError, ValueError):
            # Never create a LogRecord containing rejected values, including
            # library exception messages, even when a developer makes a mistake.
            safe = event("diagnostic.rejected")
        logging.getLogger("onpc." + CATALOG[safe["event"]]["domain"]).log(
            LEVELS[level], describe(safe), extra={"onpc_event": True, "onpc_payload": encode(safe)})

    def debug(self, event_id, *values, **named):
        self._emit("DEBUG", event_id, values, named)

    def info(self, event_id, *values, **named):
        self._emit("INFO", event_id, values, named)

    def warning(self, event_id, *values, **named):
        self._emit("WARNING", event_id, values, named)

    def error(self, event_id, *values, **named):
        self._emit("ERROR", event_id, values, named)

    def critical(self, event_id, *values, **named):
        self._emit("CRITICAL", event_id, values, named)


def get_logger(domain):
    if domain not in {entry["domain"] for entry in CATALOG.values()}:
        raise ValueError("Invalid diagnostic domain")
    return EventLogger(domain)


def record_payload(record):
    # Third-party logging is deliberately not copied into diagnostics. Never
    # call getMessage(), format(), handleError(), or inspect traceback locals.
    if (getattr(record, "onpc_event", False) is not True or record.args
            or record.exc_info or record.stack_info):
        return encode(event("diagnostic.unclassified"))
    try:
        return encode(decode(getattr(record, "onpc_payload", None)))
    except (ValueError, TypeError):
        return encode(event("diagnostic.rejected"))


class ConsoleHandler(logging.Handler):
    def emit(self, record):
        try:
            sys.stderr.write(describe(decode(record_payload(record))) + "\n")
        except Exception:
            pass


def configure_console():
    root = logging.getLogger()
    root.handlers.clear()
    root.addHandler(ConsoleHandler())
    root.setLevel(logging.INFO)


def operation_scope(callback):
    @wraps(callback)
    def scoped(*args, **kwargs):
        with operation():
            return callback(*args, **kwargs)
    return scoped


def log_version():
    # Read only the packaged version, never uname/hostnames/environment dumps.
    version = "unknown"
    paths = (Path(__file__).resolve().parents[2] / "data" / "app.json",
             Path("/usr/share/oh-no-parent-control/app.json"))
    for path in paths:
        try:
            candidate = json.loads(path.read_text(encoding="utf-8"))["version"]
            version = _field({"type": "version"}, candidate)
            break
        except (OSError, ValueError, TypeError, KeyError):
            continue
    get_logger("runtime").info("runtime.version", version=version)


# Only shipped module names are eligible fault locations. Never retain a
# traceback filename, source line, local variable, or unknown module name.
FAULT_SOURCES = {
    "oh_no_parent_control.data_migration": "migration",
    "broker.oh_no_parent_control.data_migration": "migration",
    "oh_no_parent_control.grant_diagnostics": "grant",
    "broker.oh_no_parent_control.grant_diagnostics": "grant",
    "oh_no_parent_control_kiosk.preview": "preview",
    "oh_no_parent_control_kiosk.preview_viewer": "preview",
    "oh_no_parent_control_parent.main": "parent",
    "parent.oh_no_parent_control_parent.main": "parent",
    "oh_no_parent_control_parent.client": "parent-client",
    "parent.oh_no_parent_control_parent.client": "parent-client",
    "oh_no_parent_control_ui.feedback_transport": "feedback-transport",
    "common.oh_no_parent_control_ui.feedback_transport": "feedback-transport",
    "oh_no_parent_control_ui.rich_text_editor": "rich-text-editor",
    "common.oh_no_parent_control_ui.rich_text_editor": "rich-text-editor",
    "oh_no_parent_control.execution_probe": "execution-probe",
    "broker.oh_no_parent_control.execution_probe": "execution-probe",
    "oh_no_parent_control.probe_generation": "execution-probe",
    "broker.oh_no_parent_control.probe_generation": "execution-probe",
    "oh_no_parent_control.extension_manager": "extension-manager",
    "broker.oh_no_parent_control.extension_manager": "extension-manager",
    "oh_no_parent_control.core": "core",
    "broker.oh_no_parent_control.core": "core",
    "oh_no_parent_control.service": "service",
    "broker.oh_no_parent_control.service": "service",
    "oh_no_parent_control.execution_policy": "execution-policy",
    "broker.oh_no_parent_control.execution_policy": "execution-policy",
    "oh_no_parent_control.app_termination": "app-termination",
    "broker.oh_no_parent_control.app_termination": "app-termination",
    "oh_no_parent_control.authorization": "authorization",
    "broker.oh_no_parent_control.authorization": "authorization",
    "oh_no_parent_control.uninstall": "uninstall",
    "broker.oh_no_parent_control.uninstall": "uninstall",
    "oh_no_parent_control.adapters": "adapters",
    "broker.oh_no_parent_control.adapters": "adapters",
    "oh_no_parent_control.probe_channel": "probe-channel",
    "broker.oh_no_parent_control.probe_channel": "probe-channel",
    "oh_no_parent_control.catalog": "catalog",
    "broker.oh_no_parent_control.catalog": "catalog",
    "oh_no_parent_control.preferences": "preferences",
    "broker.oh_no_parent_control.preferences": "preferences",
    "oh_no_parent_control_ui.feedback": "feedback",
    "common.oh_no_parent_control_ui.feedback": "feedback",
    "oh_no_parent_control_ui.diagnostics": "diagnostics",
    "common.oh_no_parent_control_ui.diagnostics": "diagnostics",
    "oh_no_parent_control_ui.errors": "errors",
    "common.oh_no_parent_control_ui.errors": "errors",
    "oh_no_parent_control_kiosk.lava": "kiosk-lava",
    "kiosk.oh_no_parent_control_kiosk.lava": "kiosk-lava",
    "oh_no_parent_control_kiosk.snowflakes": "kiosk-snowflakes",
    "kiosk.oh_no_parent_control_kiosk.snowflakes": "kiosk-snowflakes",
    "oh_no_parent_control_kiosk.floating_islands": "kiosk-floating-islands",
    "kiosk.oh_no_parent_control_kiosk.floating_islands": "kiosk-floating-islands",
    "oh_no_parent_control_kiosk.thunder": "kiosk-thunder",
    "kiosk.oh_no_parent_control_kiosk.thunder": "kiosk-thunder",
    "oh_no_parent_control_kiosk.selection_store": "kiosk-selection-store",
    "kiosk.oh_no_parent_control_kiosk.selection_store": "kiosk-selection-store",
    "oh_no_parent_control_kiosk.main": "kiosk",
    "kiosk.oh_no_parent_control_kiosk.main": "kiosk"
}


def record_exception(error):
    source, line = "other", 0
    current = error.__traceback__
    for _ in range(128):
        if current is None:
            break
        module = current.tb_frame.f_globals.get("__name__")
        if type(module) is str and module in FAULT_SOURCES:
            source = FAULT_SOURCES[module]
            line = min(50000, max(0, current.tb_lineno))
        current = current.tb_next
    get_logger("runtime").error("runtime.fault", error_type=error_code(error), source=source, line=line)


def run_cli(callback):
    """Command entrypoints must not dump chained exceptions to the journal."""
    sys.excepthook = lambda _kind, error, _traceback: record_exception(error)
    threading.excepthook = lambda args: record_exception(args.exc_value)
    try:
        return callback()
    except Exception as error:
        record_exception(error)
        return 1
